services:
  app:
    container_name: organization-service
    build:
      context: ./app
      dockerfile: Dockerfile
    command: [ "sh", "scripts/entrypoint.sh" ]
    env_file:
      - envs/docker/app.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
  db:
    container_name: organization-service-db
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
